'use strict';
let width = 8;
let height = 5;
let area = width * height;
console.log('value of area: ', area);
console.log('typeof area: ', typeof area);
let bill = 100;
let payment = 500;
let change = payment - bill;
console.log('value of change: ', change);
console.log('typeof change: ', typeof change);
let quizzes = 10;
let midterm = 40;
let final = 40;
let grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('typeof grade: ', typeof grade);
let firstName = 'Connie';
let lastName = 'Chin';
let fullName = firstName + ' ' + lastName;
console.log('value of FullName: ', fullName);
console.log('typeof fullName: ', typeof fullName);
let pH = 9;
let isAcidic = pH < 7;
console.log('value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof isAcidic);
let headCount = 222;
let isSparta = headCount === 300;
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof isSparta);
let motto = fullName + ' is the GOAT';
console.log('value of motto: ', motto);
console.log('typeof motto: ', typeof motto);
